name: muzikplayer
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  http: ^0.12.0+3
  rflutter_alert: ^1.0.3
  audioplayers: ^0.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:

    - assets/




